In [2]:
import numpy as np
arr2 = np.array([[1,2,3,4,5],[5,6,7,8]])

In [3]:
print(arr2)

[list([1, 2, 3, 4, 5]) list([5, 6, 7, 8])]


In [4]:
print(arr2.ndim)

1


In [6]:
print(arr2.shape)

(2,)


In [7]:
print(arr2.dtype)

object


In [8]:
arry=np.zeros(10)

In [9]:
print(arry)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
arr1=np.zeros((5,5))

In [11]:
print(arr1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
print(arr1.ndim)

2


In [13]:
print(arr1.dtype)

float64


In [14]:
arr4=np.empty((5,5),dtype=int)

In [15]:
print(arr4)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [16]:
print(arr4.ndim)

2


In [18]:
np.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [19]:
arr6=np.arange(10,100,5)
print(arr6)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [20]:
print(arr6.ndim)

1


In [22]:
print(arr6.shape)

(18,)


In [26]:
arr4=np.arange(1,13,1)

In [27]:
arr6=arr4.reshape(4,3)

In [28]:
print(arr6)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [29]:
print(arr4)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [31]:
arr3=arr4.reshape(2,2,-1)

In [32]:
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [36]:
arr10=np.arange(10)

In [37]:
for n in arr10:
    print(n)

0
1
2
3
4
5
6
7
8
9


In [38]:
arr11=np.array([[1,2,3,4],[5,6,7,8]])

In [40]:
for n in arr11:
    print(n)


[1 2 3 4]
[5 6 7 8]


In [41]:
for n in np.nditer(arr11):
    print(n)

1
2
3
4
5
6
7
8


In [42]:
for n in np.nditer(arr11[:,::2]):
    print(n)

1
3
5
7


In [47]:
arr=np.array([[1,2,3]])

In [48]:
arr1.swapaxes(0,1)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])