In [4]:
import numpy as np
arr1=[1,2,3,4,5,6,7,8,9]
arr2=[11,12,13,14,15,16,17,18]
z=[]
for i, j in zip(arr1,arr2):
    z.append(i+j)
    
z

[12, 14, 16, 18, 20, 22, 24, 26]

In [6]:
fname=("Alex","Jill","Tay")
lname=("Kennedy","Charles","Martin")
flname=zip(fname,lname)
print(tuple(flname))

(('Alex', 'Kennedy'), ('Jill', 'Charles'), ('Tay', 'Martin'))


In [8]:
last1=[1,2,3,4,5,6]
last2=[10,11,12,13,14,15]
print(list(zip(last1,last2)))

[(1, 10), (2, 11), (3, 12), (4, 13), (5, 14), (6, 15)]


In [9]:
import numpy as np
arr=np.arange(21)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [10]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [13]:
arr=np.random.randn(10)

In [14]:
arr

array([ 0.57503531, -0.16471745, -0.30809292, -0.5085939 , -0.58436836,
       -0.80465158,  0.08345863,  2.35979659, -0.8457412 ,  0.67632427])

In [15]:
arr1=np.arange(20)

In [16]:
arr1=np.random.randn(10)

In [17]:
np.add(arr,arr1)

array([-0.45783488, -1.97064332,  1.12457809, -1.93180238, -1.2342569 ,
       -1.81148177,  0.11348205,  2.67206032, -1.19879767,  0.07731359])

In [18]:
np.maximum(arr1,arr)

array([ 0.57503531, -0.16471745,  1.43267101, -0.5085939 , -0.58436836,
       -0.80465158,  0.08345863,  2.35979659, -0.35305647,  0.67632427])

In [20]:
arr= np.arange(9).reshape((3,3))

arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
np.where(arr<4,-1,-2)

array([[-1, -1, -1],
       [-1, -2, -2],
       [-2, -2, -2]])

In [22]:
np.where((arr<4)&(arr>2),-1,-2)

array([[-2, -2, -2],
       [-1, -2, -2],
       [-2, -2, -2]])

In [23]:
print(arr<4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [24]:
arr4=[10,11,12,13,14,15,16]

In [25]:
arr3 = [r1 if c else r2 for r1,r2,c in zip(arr1,arr2,arr4)]

arr3

[-1.0328701894617083,
 -1.8059258685804538,
 1.4326710091530566,
 -1.423208479825025,
 -0.6498885422634242,
 -1.0068301957792076,
 0.0300234230221559]