In [1]:
import numpy as np

In [2]:
my_list=[11,22,33,44,55,66,77,88]

In [3]:
print(my_list)

[11, 22, 33, 44, 55, 66, 77, 88]


In [4]:
my_arr=np.array(my_list)

In [5]:
print(my_arr.dtype)

int32


In [6]:
fruits =['orange','apple','cherry','grape']

In [7]:
my_strArr = np.array(fruits)

In [8]:
print(my_strArr.dtype)

<U6


In [9]:
myarr=np.array([11,22,33,44,55],dtype='S')

In [10]:
print(myarr.dtype)

|S2


In [14]:
myarr2=np.array([11,22,33,44,55],dtype='i')

In [15]:
print(myarr2.dtype)

int32


In [17]:
scores=np.array([78.5,42,88,93.1])

In [18]:
print(scores)

[78.5 42.  88.  93.1]


In [19]:
arr4=scores.astype('i')

In [20]:
print(arr4.dtype)

int32


In [21]:
print(arr4.ndim)

1


In [23]:
arr4[2]=4

In [24]:
print(arr4.base)

None


In [25]:
print(myarr2.base)

None


In [26]:
lst = [1,2,3,4,5]
lst2 = [11,22,33,44,55]
lst3=[lst,lst2]

In [27]:
turtles=np.array(lst3)

In [28]:
print(turtles)
print(turtles.ndim)

[[ 1  2  3  4  5]
 [11 22 33 44 55]]
2


In [29]:
print(turtles.shape)

(2, 5)


In [30]:
arr4[2]=4


In [32]:
myarr2=np.array(lst3,dtype='i')

In [33]:
print(myarr2)

[[ 1  2  3  4  5]
 [11 22 33 44 55]]


In [36]:
bool_ar=np.array(lst3,dtype="i")

In [37]:
print(bool_ar)

[[ 1  2  3  4  5]
 [11 22 33 44 55]]
